// Package tasks provides a per-project task store keyed by harp IDs
// (see github.com/ctxloom/shared/harp). The source of truth is an append-only
// JSONL event log at ~/.ctxloom/tasks/<project-id>.jsonl (ADR 0025); current
// state is the fold of its events.
package tasks

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"strings"

	"github.com/ctxloom/shared/harp"
)

// Default status names. Hardcoded in v1; revisit if user-defined statuses
// become a real need.
const (
	StatusInProgress = "In Progress"
	StatusToDo       = "To Do"
	StatusDeferred   = "Deferred"
	StatusDone       = "Done"
	StatusArchived   = "Archived"
)

// DefaultStatusOrder is the canonical status ordering for display.
var DefaultStatusOrder = []string{StatusInProgress, StatusToDo, StatusDeferred, StatusDone, StatusArchived}

// ErrTriggerRequired is returned when a task is set Deferred without a trigger.
// A Deferred task is parked on a named wake-up condition (mirroring an ADR
// revive trigger), so the condition must be supplied.
var ErrTriggerRequired = errors.New("a Deferred task requires a non-empty trigger (the condition that should revive it)")

// ValidateStatusTrigger enforces the Deferred invariant: a task may only be
// Deferred when it carries a non-empty trigger. The store calls this before
// persisting an add or status change, so the CLI and MCP paths share one rule.
func ValidateStatusTrigger(status, trigger string) error {
	if status == StatusDeferred && strings.TrimSpace(trigger) == "" {
		return ErrTriggerRequired
	}
	return nil
}

// Task is one row in the store.
type Task struct {
	HarpID   string // "swift-amber-falcon" — generated by shared/harp
	Text     string // trimmed, no harp ID inside
	Status   string // one of DefaultStatusOrder or user-supplied
	Checked  bool   // true when status is Done/Archived
	TextHash string // sha256(trimmed text), hex-encoded, first 12 chars

	// Trigger is the named wake-up condition for a Deferred task: a free-text
	// description of what should revive it, in the spirit of an ADR revive
	// trigger. Required when Status is Deferred; preserved across status
	// changes so a task re-deferred later keeps its condition unless a new one
	// is supplied. Empty for non-Deferred tasks that never carried one.
	Trigger string

	// OriginSession is the harp of the session that created the task, from the
	// `add` event; empty for tasks added outside a session.
	OriginSession string
}

// Summary holds counts per status and the harp IDs currently in-progress.
type Summary struct {
	Counts     map[string]int
	InProgress []string
}

// effectiveTrigger picks the trigger to persist on a status change: a non-empty
// new value wins, otherwise the task's existing trigger is preserved.
func effectiveTrigger(newTrigger, existing string) string {
	if t := strings.TrimSpace(newTrigger); t != "" {
		return t
	}
	return existing
}

func statusIsDone(status string) bool {
	return status == StatusDone || status == StatusArchived
}

func hashText(s string) string {
	h := sha256.Sum256([]byte(strings.TrimSpace(s)))
	return hex.EncodeToString(h[:])[:12]
}

// uniqueHarpIDFromSet picks a fresh short harp id not already in `used`. Tasks
// use the two-word short harp (adj-noun): per-project task counts are small, so
// the smaller identity space is ample and the ids stay tidy in the list. 100
// attempts is overkill against the name space and a small set; the log backend's
// mint-with-check (and the fold-and-repair pass) cover the residual case.
func uniqueHarpIDFromSet(used map[string]struct{}) string {
	for range 100 {
		id := harp.GenerateShortName()
		if _, dup := used[id]; !dup {
			return id
		}
	}
	return harp.GenerateShortName()
}

func filterTasks(all []Task, statuses []string, term string) []Task {
	var statusSet map[string]bool
	if len(statuses) > 0 {
		statusSet = make(map[string]bool, len(statuses))
		for _, s := range statuses {
			statusSet[s] = true
		}
	}
	termLower := strings.ToLower(strings.TrimSpace(term))
	out := make([]Task, 0, len(all))
	for _, t := range all {
		if statusSet != nil && !statusSet[t.Status] {
			continue
		}
		if termLower != "" && !strings.Contains(strings.ToLower(t.Text), termLower) {
			continue
		}
		out = append(out, t)
	}
	return out
}
